using System.Text;

namespace EtwLttng;

internal static class Emitter
{
    public static void Emit(IReadOnlyList<TraceEvent> events, string outDir)
    {
        Directory.CreateDirectory(outDir);

        EmitTracepointsHeader(events, Path.Combine(outDir, "ese_tracepoints.h"));
        EmitProvider(events, Path.Combine(outDir, "ese_tracepoint_provider.cxx"));
        EmitTable(events, Path.Combine(outDir, "ese_tracepoint_table.h"));
        EmitDispatch(events, Path.Combine(outDir, "oseventtrace_dispatch.g.cxx"));
    }


    //  ===== ese_tracepoints.h =====
    private static void EmitTracepointsHeader(IReadOnlyList<TraceEvent> events, string path)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//  Generated by tools/etwlttng — do not edit.");
        sb.AppendLine();
        sb.AppendLine("#undef TRACEPOINT_PROVIDER");
        sb.AppendLine("#define TRACEPOINT_PROVIDER ese");
        sb.AppendLine();
        sb.AppendLine("#undef TRACEPOINT_INCLUDE");
        sb.AppendLine("#define TRACEPOINT_INCLUDE \"ese_tracepoints.h\"");
        sb.AppendLine();
        sb.AppendLine("#if !defined(_ESE_TRACEPOINTS_H) || defined(TRACEPOINT_HEADER_MULTI_READ)");
        sb.AppendLine("#define _ESE_TRACEPOINTS_H");
        sb.AppendLine();
        sb.AppendLine("#include <lttng/tracepoint.h>");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine();

        foreach (var ev in events)
        {
            EmitOneTracepoint(sb, ev);
        }

        sb.AppendLine("#endif // _ESE_TRACEPOINTS_H");
        sb.AppendLine();
        sb.AppendLine("#include <lttng/tracepoint-event.h>");

        File.WriteAllText(path, sb.ToString());
    }

    private static void EmitOneTracepoint(StringBuilder sb, TraceEvent ev)
    {
        sb.Append("TRACEPOINT_EVENT(ese, ").Append(ev.Name).AppendLine(",");

        //  TP_ARGS: typed fields, plus an optional overflow `const char*`
        //  when the event has more than (MaxTypedFields + 1) fields.
        var typed = ev.TypedFields;
        var hasOverflow = ev.HasOverflow;
        sb.Append("    TP_ARGS(");
        if (typed.Count == 0 && !hasOverflow)
        {
            sb.AppendLine("),");
        }
        else
        {
            sb.AppendLine();
            for (var i = 0; i < typed.Count; i++)
            {
                var f = typed[i];
                sb.Append("        ").Append(TypeMap.TrampolineParamType(f)).Append(", ").Append(f.Name);
                var last = !hasOverflow && i + 1 == typed.Count;
                sb.AppendLine(last ? "" : ",");
            }
            if (hasOverflow)
            {
                sb.AppendLine("        const char*, overflow");
            }
            sb.AppendLine("    ),");
        }

        //  TP_FIELDS: ctf_* per typed field + the overflow string.
        sb.AppendLine("    TP_FIELDS(");
        foreach (var f in typed)
        {
            sb.Append("        ").AppendLine(TypeMap.CtfMacro(f));
        }
        if (hasOverflow)
        {
            sb.AppendLine("        ctf_string( overflow, overflow != nullptr ? overflow : \"\" )");
        }
        sb.AppendLine("    )");

        sb.AppendLine(")");
        sb.AppendLine();

        sb.Append("TRACEPOINT_LOGLEVEL(ese, ").Append(ev.Name).Append(", ").Append(LogLevelFor(ev.Level)).AppendLine(")");
        sb.AppendLine();
    }

    private static string LogLevelFor(string winLevel) => winLevel switch
    {
        "win:Critical" => "TRACE_CRIT",
        "win:Error" => "TRACE_ERR",
        "win:Warning" => "TRACE_WARNING",
        "win:Informational" => "TRACE_INFO",
        "win:Verbose" => "TRACE_DEBUG",
        _ => "TRACE_DEBUG",
    };


    //  ===== ese_tracepoint_provider.cxx =====
    private static void EmitProvider(IReadOnlyList<TraceEvent> events, string path)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//  Generated by tools/etwlttng — do not edit.");
        sb.AppendLine();
        sb.AppendLine("#define TRACEPOINT_CREATE_PROBES");
        sb.AppendLine("#define TRACEPOINT_DEFINE");
        sb.AppendLine();
        sb.AppendLine("#include \"ese_tracepoints.h\"");
        sb.AppendLine("#include \"ese_tracepoint_table.h\"");
        sb.AppendLine();

        sb.AppendLine("extern \"C\" {");
        sb.AppendLine();
        foreach (var ev in events)
        {
            EmitTrampoline(sb, ev);
        }
        sb.AppendLine("} // extern \"C\"");
        sb.AppendLine();

        sb.AppendLine("namespace");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine("EseTracepointTable g_table = {");
        sb.AppendLine("    .version = ESE_TRACEPOINT_TABLE_VERSION,");
        foreach (var ev in events)
        {
            sb.Append("    .pfn_").Append(ev.Name).Append(" = &EseTracepoint_").Append(ev.Name).AppendLine(",");
        }
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("} // anonymous namespace");
        sb.AppendLine();

        sb.AppendLine("extern \"C\" __attribute__((visibility(\"default\")))");
        sb.AppendLine("const EseTracepointTable* EseTracepointGetTable()");
        sb.AppendLine("{");
        sb.AppendLine("    return &g_table;");
        sb.AppendLine("}");

        File.WriteAllText(path, sb.ToString());
    }

    private static void EmitTrampoline(StringBuilder sb, TraceEvent ev)
    {
        sb.Append("void EseTracepoint_").Append(ev.Name).Append("(");
        var typed = ev.TypedFields;
        var hasOverflow = ev.HasOverflow;
        if (typed.Count == 0 && !hasOverflow)
        {
            sb.AppendLine(")");
        }
        else
        {
            sb.AppendLine();
            for (var i = 0; i < typed.Count; i++)
            {
                var f = typed[i];
                var last = !hasOverflow && i + 1 == typed.Count;
                sb.Append("    ").Append(TypeMap.TrampolineParamType(f)).Append(" ").Append(f.Name);
                sb.AppendLine(last ? ")" : ",");
            }
            if (hasOverflow)
            {
                sb.AppendLine("    const char* overflow )");
            }
        }
        sb.AppendLine("{");
        sb.Append("    tracepoint(ese, ").Append(ev.Name);
        foreach (var f in typed)
        {
            sb.Append(", ").Append(f.Name);
        }
        if (hasOverflow)
        {
            sb.Append(", overflow");
        }
        sb.AppendLine(");");
        sb.AppendLine("}");
        sb.AppendLine();
    }


    //  ===== ese_tracepoint_table.h =====
    private static void EmitTable(IReadOnlyList<TraceEvent> events, string path)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//  Generated by tools/etwlttng — do not edit.");
        sb.AppendLine();
        sb.AppendLine("#ifndef ESE_TRACEPOINT_TABLE_H");
        sb.AppendLine("#define ESE_TRACEPOINT_TABLE_H");
        sb.AppendLine();
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine();
        sb.AppendLine("//  Bump on every signature-incompatible change.  libese.so checks");
        sb.AppendLine("//  the version after dlopen and refuses a mismatch.");
        sb.AppendLine("#define ESE_TRACEPOINT_TABLE_VERSION 1u");
        sb.AppendLine();
        sb.AppendLine("#ifdef __cplusplus");
        sb.AppendLine("extern \"C\" {");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("struct EseTracepointTable");
        sb.AppendLine("{");
        sb.AppendLine("    uint32_t version;");
        sb.AppendLine();

        foreach (var ev in events)
        {
            EmitTableEntry(sb, ev);
        }

        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("typedef const struct EseTracepointTable* ( *EseTracepointGetTableFn )( void );");
        sb.AppendLine();
        sb.AppendLine("#ifdef __cplusplus");
        sb.AppendLine("} // extern \"C\"");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("#endif // ESE_TRACEPOINT_TABLE_H");

        File.WriteAllText(path, sb.ToString());
    }

    private static void EmitTableEntry(StringBuilder sb, TraceEvent ev)
    {
        sb.Append("    void ( *pfn_").Append(ev.Name).Append(" )(");
        var typed = ev.TypedFields;
        var hasOverflow = ev.HasOverflow;
        if (typed.Count == 0 && !hasOverflow)
        {
            sb.AppendLine(");");
            return;
        }
        sb.AppendLine();
        for (var i = 0; i < typed.Count; i++)
        {
            var f = typed[i];
            var last = !hasOverflow && i + 1 == typed.Count;
            sb.Append("        ").Append(TypeMap.TrampolineParamType(f)).Append(" ").Append(f.Name);
            sb.AppendLine(last ? " );" : ",");
        }
        if (hasOverflow)
        {
            sb.AppendLine("        const char* overflow );");
        }
    }


    //  ===== oseventtrace_dispatch.g.cxx =====
    //
    //  One static handler per event so each has its own stack frame
    //  (otherwise the 77-case switch's locals — buffers for UTF-8 and
    //  overflow text — all get rolled into OSEventTrace_'s frame and
    //  blow the smaller thread stacks).  OSEventTrace_ becomes a thin
    //  switch that calls the right handler by pointer.
    private static void EmitDispatch(IReadOnlyList<TraceEvent> events, string path)
    {
        var sb = new StringBuilder();
        sb.AppendLine("//  Generated by tools/etwlttng — do not edit.");
        sb.AppendLine();
        sb.AppendLine("//  Included by oseventtrace_posix.cxx.  Defines one static");
        sb.AppendLine("//  per-event handler and a switch that fans out to them.");
        sb.AppendLine();

        //  __attribute__((noinline)) keeps the compiler from merging
        //  the handlers back into OSEventTrace_'s frame.  We *want*
        //  the function-call indirection so each handler has its own
        //  stack frame.
        foreach (var ev in events)
        {
            EmitDispatchHandler(sb, ev);
        }

        sb.AppendLine();
        sb.AppendLine("static void EseTpDispatch( const ULONG etguid, va_list ap, const EseTracepointTable * pTable )");
        sb.AppendLine("{");
        sb.AppendLine("    switch ( etguid )");
        sb.AppendLine("    {");
        foreach (var ev in events)
        {
            sb.Append("        case _etguid").Append(ev.Name)
              .Append(": EseTpDispatchHandler_").Append(ev.Name).AppendLine("( ap, pTable ); break;");
        }
        sb.AppendLine("        default: break;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(path, sb.ToString());
    }

    private static void EmitDispatchHandler(StringBuilder sb, TraceEvent ev)
    {
        sb.Append("__attribute__((noinline)) static void EseTpDispatchHandler_")
          .Append(ev.Name)
          .AppendLine("( va_list ap, const EseTracepointTable * pTable )");
        sb.AppendLine("{");
        sb.Append("    if ( pTable->pfn_").Append(ev.Name).AppendLine(" == nullptr )");
        sb.AppendLine("    {");
        sb.AppendLine("        return;");
        sb.AppendLine("    }");

        //  Unpack every field (typed + overflow) into a local.
        for (var i = 0; i < ev.Fields.Count; i++)
        {
            var f = ev.Fields[i];
            EmitFieldUnpack(sb, f);
        }

        //  Build the overflow string when needed.
        if (ev.HasOverflow)
        {
            EmitOverflowFormat(sb, ev);
        }

        //  Call the table fn.
        sb.Append("    pTable->pfn_").Append(ev.Name).Append("(");
        var typed = ev.TypedFields;
        var hasOverflow = ev.HasOverflow;
        if (typed.Count == 0 && !hasOverflow)
        {
            sb.AppendLine(");");
        }
        else
        {
            sb.AppendLine();
            for (var i = 0; i < typed.Count; i++)
            {
                var f = typed[i];
                var last = !hasOverflow && i + 1 == typed.Count;
                sb.Append("        arg_").Append(f.Name);
                sb.AppendLine(last ? " );" : ",");
            }
            if (hasOverflow)
            {
                sb.AppendLine("        overflow_buf );");
            }
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitFieldUnpack(StringBuilder sb, TraceField f)
    {
        switch (f.InType)
        {
            case WinType.UnicodeString:
                sb.Append("    const uint16_t* wsz_").Append(f.Name)
                  .Append(" = ").Append(TypeMap.VaArgUnpack(f)).AppendLine(";");
                sb.Append("    char utf8_").Append(f.Name).AppendLine("[ 2048 ];");
                sb.Append("    EseTpDispatchWideToUtf8( wsz_").Append(f.Name)
                  .Append(", utf8_").Append(f.Name)
                  .Append(", sizeof( utf8_").Append(f.Name).AppendLine(" ) );");
                sb.Append("    const char* arg_").Append(f.Name)
                  .Append(" = utf8_").Append(f.Name).AppendLine(";");
                break;
            case WinType.AnsiString:
                sb.Append("    const char* arg_").Append(f.Name)
                  .Append(" = ").Append(TypeMap.VaArgUnpack(f)).AppendLine(";");
                break;
            case WinType.Guid:
            case WinType.Binary:
                sb.Append("    const uint8_t* arg_").Append(f.Name)
                  .Append(" = ").Append(TypeMap.VaArgUnpack(f)).AppendLine(";");
                break;
            default:
                sb.Append("    const ").Append(TypeMap.ScalarCType(f.InType))
                  .Append(" arg_").Append(f.Name)
                  .Append(" = ").Append(TypeMap.VaArgUnpack(f)).AppendLine(";");
                break;
        }
    }

    private static void EmitOverflowFormat(StringBuilder sb, TraceEvent ev)
    {
        var overflow = ev.OverflowFields;
        sb.AppendLine("    char overflow_buf[ 1024 ];");

        var fmt = new StringBuilder();
        var args = new List<string>();
        for (var i = 0; i < overflow.Count; i++)
        {
            var f = overflow[i];
            if (i > 0)
            {
                fmt.Append(' ');
            }
            fmt.Append(f.Name).Append('=').Append(TypeMap.OverflowFormatSpec(f));
            var argExpr = TypeMap.OverflowFormatArg(f);
            if (!string.IsNullOrEmpty(argExpr))
            {
                args.Add(argExpr);
            }
        }

        sb.Append("    snprintf( overflow_buf, sizeof( overflow_buf ), \"")
          .Append(fmt)
          .Append("\"");
        foreach (var arg in args)
        {
            sb.Append(", ").Append(arg);
        }
        sb.AppendLine(" );");
    }
}
