// POSIX equivalent of os/oseventtrace.cxx. Upstream wraps the autogenerated
// MOF/ETW provider; on Linux there's no ETW until Phase 7 wires this up to
// LTTng. Until then we provide:
//
//   - Lifecycle entry points (no-ops)
//   - OSEventTrace_ accepting the same varargs surface as the engine, with a
//     no-op body so callers don't crash. The compile-time-disabled
//     FOSEventTraceEnabled() guard means the engine essentially never enters
//     this function in practice
//   - FOSEventTraceEnabled<>() always returning fFalse so the engine's
//     conditional trace points compile out at runtime
//   - COSEventTraceIdCheck::FAnnounceTime<>() always returning fFalse for the
//     handful of GUIDs that get explicitly instantiated in the header

#include "osstd.hxx"


////////////////////////////////////////////////
//  Lifecycle

void OSEventTracePostterm() {}
BOOL FOSEventTracePreinit() { return fTrue; }
void OSEventTraceTerm()     {}
ERR  ErrOSEventTraceInit()  { return JET_errSuccess; }


////////////////////////////////////////////////
//  Trace recording
//
//  We don't have ETW or LTTng wired up, so OSEventTrace_ is a no-op
//  for every guid except the three EventLog ones — those carry the
//  formatted message text emitted by OSEventReportEvent (event.cxx)
//  via ETEventLogInfo/Warn/Error, and we route them to stderr so
//  events are actually visible during runs.
//
//  Each EventLog ET* wrapper passes cData=1 and a single wchar_t*
//  argument.  Engine wchar_t is 16-bit (-fshort-wchar); libc's "%ls"
//  expects native 32-bit wchar_t, so we down-convert via
//  WideCharToMultiByte (UTF-8) before writing.

namespace
{

void EmitEventLogLine( const char* szSev, const wchar_t* wsz )
{
    if ( wsz == nullptr )
    {
        return;
    }
    char nbuf[ 8192 ];
    const int cbN = WideCharToMultiByte( CP_UTF8, 0, wsz, -1,
                                         nbuf, (int)sizeof( nbuf ),
                                         nullptr, nullptr );
    if ( cbN <= 0 )
    {
        return;
    }
    //  cbN includes the trailing NUL; trim it from the write.
    const size_t cb = (size_t)( cbN - 1 );
    fprintf( stderr, "[ese %s] ", szSev );
    fwrite( nbuf, 1, cb, stderr );
    fputc( '\n', stderr );
}

}  // namespace

void __cdecl OSEventTrace_( const ULONG etguid,
                            const size_t cData,
                            ... )
{
    if ( etguid != _etguidEventLogInfo &&
         etguid != _etguidEventLogWarn &&
         etguid != _etguidEventLogError )
    {
        return;
    }
    if ( cData < 1 )
    {
        return;
    }

    va_list ap;
    va_start( ap, cData );
    const wchar_t* wsz = va_arg( ap, const wchar_t* );
    va_end( ap );

    const char* sev = ( etguid == _etguidEventLogError ) ? "ERROR"
                    : ( etguid == _etguidEventLogWarn  ) ? "WARN"
                    :                                       "INFO";
    EmitEventLogLine( sev, wsz );
}


////////////////////////////////////////////////
//  Compile-time / runtime trace gates — always off
//
//  The header declares these as INLINE BOOL FOSEventTraceEnabled() and the
//  templated overload, plus extern template instantiations for the GUIDs
//  ESE actually checks. We provide the explicit instantiations here so the
//  engine links; all return fFalse so trace blocks are skipped.

//  Both FOSEventTraceEnabled overloads now have inline bodies in
//  oseventtrace.hxx (return fFalse). The explicit template
//  instantiations below still bind to the generic templated body
//  there, so the engine links for code paths that use the templated
//  form (e.g. `FOSEventTraceEnabled< _etguidCacheRequestPage >()`).

template BOOL FOSEventTraceEnabled< _etguidCacheRequestPage >();
template BOOL FOSEventTraceEnabled< _etguidCacheMemoryUsage >();
template BOOL FOSEventTraceEnabled< _etguidInstStationId >();
template BOOL FOSEventTraceEnabled< _etguidDiskStationId >();
template BOOL FOSEventTraceEnabled< _etguidFileStationId >();
template BOOL FOSEventTraceEnabled< _etguidSysStationId >();
template BOOL FOSEventTraceEnabled< _etguidIsamDbfilehdrInfo >();
template BOOL FOSEventTraceEnabled< _etguidFmpStationId >();

//  FAnnounceTime is INLINE in the header — only the explicit template
//  instantiations are needed here.
template BOOL COSEventTraceIdCheck::FAnnounceTime< _etguidInstStationId >( const TraceStationIdentificationReason );
template BOOL COSEventTraceIdCheck::FAnnounceTime< _etguidDiskStationId >( const TraceStationIdentificationReason );
template BOOL COSEventTraceIdCheck::FAnnounceTime< _etguidFileStationId >( const TraceStationIdentificationReason );
template BOOL COSEventTraceIdCheck::FAnnounceTime< _etguidSysStationId >( const TraceStationIdentificationReason );
template BOOL COSEventTraceIdCheck::FAnnounceTime< _etguidIsamDbfilehdrInfo >( const TraceStationIdentificationReason );
template BOOL COSEventTraceIdCheck::FAnnounceTime< _etguidFmpStationId >( const TraceStationIdentificationReason );
