// Copyright (c) Jake Helfert
// Licensed under the MIT License.
//
// POSIX equivalent of os/oseventtrace.cxx.  Upstream wraps the
// autogenerated MOF/ETW provider; on Linux this layer is the dispatch
// point for the optional LTTng UST provider that lives in
// libese_tracepoints.so.
//
// Loading model: the engine's libese.so does NOT hard-link lttng-ust.
// At first use we `dlopen("libese_tracepoints.so", RTLD_LAZY)` and
// look up a single C-linkage symbol — `EseTracepointGetTable` — which
// returns a struct of function pointers (one per tracepoint).  If
// either the .so or the symbol is missing, the table pointer stays
// null and every dispatch is a quiet no-op.  Boxes without lttng-ust
// installed therefore see no behaviour change.
//
// All four files driving this — the table header, the .so trampoline
// source, the LTTng TRACEPOINT_EVENT defs, and the OSEventTrace_
// dispatch body — are emitted by `tools/etwlttng` from
// `EseEtwEventsPregen.txt`.  Regeneration is wired through the
// `gen_etwlttng` CMake target.

#include "osstd.hxx"

#include "ese_tracepoint_table.h"

#include <dlfcn.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>


namespace
{


//  -------- loader state --------

const EseTracepointTable * g_pTracepointTable = nullptr;
void *                     g_phTracepointsSo  = nullptr;
pthread_once_t             g_onceInit         = PTHREAD_ONCE_INIT;


void TracepointsInitOnce()
{
    //  RTLD_LOCAL keeps lttng-ust symbols out of the global namespace
    //  so a host process embedding ESE doesn't accidentally satisfy
    //  its own lttng-ust references against ours.
    g_phTracepointsSo = dlopen( "libese_tracepoints.so", RTLD_LAZY | RTLD_LOCAL );
    if ( g_phTracepointsSo == nullptr )
    {
        return;
    }

    auto pfnGetTable = reinterpret_cast<EseTracepointGetTableFn>(
        dlsym( g_phTracepointsSo, "EseTracepointGetTable" ) );
    if ( pfnGetTable == nullptr )
    {
        return;
    }

    const EseTracepointTable * pTable = pfnGetTable();
    if ( pTable == nullptr || pTable->version != ESE_TRACEPOINT_TABLE_VERSION )
    {
        return;
    }

    g_pTracepointTable = pTable;
}


void TracepointsEnsureInit()
{
    pthread_once( &g_onceInit, TracepointsInitOnce );
}


//  -------- helpers for the generated dispatch --------

//  Convert a 16-bit-WCHAR NUL-terminated string into UTF-8 in a
//  caller-supplied buffer.  The dispatch generator calls this for
//  every win:UnicodeString field so the trampoline can take char*
//  (which lttng-ust's ctf_string consumes).
void EseTpDispatchWideToUtf8( const uint16_t * wsz, char * utf8, size_t cbUtf8 )
{
    if ( cbUtf8 == 0 )
    {
        return;
    }
    if ( wsz == nullptr )
    {
        utf8[ 0 ] = '\0';
        return;
    }
    const int cb = WideCharToMultiByte( CP_UTF8, 0,
                                        reinterpret_cast<const WCHAR*>( wsz ), -1,
                                        utf8, (int)cbUtf8,
                                        nullptr, nullptr );
    if ( cb <= 0 )
    {
        utf8[ 0 ] = '\0';
    }
}


#include "oseventtrace_dispatch.g.cxx"

} // anonymous namespace


////////////////////////////////////////////////
//  Lifecycle

void OSEventTracePostterm()
{
}

BOOL FOSEventTracePreinit()
{
    TracepointsEnsureInit();
    return fTrue;
}

void OSEventTraceTerm()
{
}

ERR ErrOSEventTraceInit()
{
    TracepointsEnsureInit();
    return JET_errSuccess;
}


////////////////////////////////////////////////
//  Trace recording — generated dispatch

void __cdecl OSEventTrace_( const ULONG etguid, const size_t cData, ... )
{
    const EseTracepointTable * pTable = g_pTracepointTable;
    if ( pTable == nullptr )
    {
        return;
    }
    (void)cData;

    va_list ap;
    va_start( ap, cData );

    EseTpDispatch( etguid, ap, pTable );

    va_end( ap );
}


////////////////////////////////////////////////
//  Per-event call-site gate
//
//  The OSEventTrace macro (oseventtrace.hxx) calls this with the event's
//  etguid *before* evaluating any trace arguments.  We read the
//  provider's per-tracepoint enable-state int — published as
//  eventEnabledState[ etguid ] by the generated table, which points at
//  lttng's `__tracepoint_ese___<Event>.state`.  When no session has the
//  event enabled the state is 0 and the whole OSEventTrace_ marshalling
//  path is skipped, mirroring how upstream gated on EventEnabled().
//  Cheap on the hot path: a couple of loads, no call into the .so once
//  the table has been resolved.
BOOL PosixTraceEnabled( const ULONG etguid )
{
    const EseTracepointTable * pTable = g_pTracepointTable;
    if ( pTable == nullptr )
    {
        //  A trace fired before the OS-layer preinit resolved the table
        //  (or there is no provider .so).  Trigger the one-shot load and
        //  re-read; stays null forever when lttng-ust isn't installed.
        TracepointsEnsureInit();
        pTable = g_pTracepointTable;
        if ( pTable == nullptr )
        {
            return fFalse;
        }
    }
    if ( etguid >= pTable->eventCount )
    {
        return fFalse;
    }
    const int * pState = pTable->eventEnabledState[ etguid ];
    return ( pState != nullptr && *pState != 0 ) ? fTrue : fFalse;
}


////////////////////////////////////////////////
//  Station-identification gate
//
//  The templated FOSEventTraceEnabled<etguid>() stays fFalse on Linux —
//  it is consulted only by COSEventTraceIdCheck::FAnnounceTime, which
//  does expensive pre-trace data-gathering for the station-id records.
//  Wiring those to the per-tracepoint enable state is separate follow-up.

template BOOL FOSEventTraceEnabled<_etguidCacheRequestPage>();

template BOOL FOSEventTraceEnabled<_etguidCacheMemoryUsage>();

template BOOL FOSEventTraceEnabled<_etguidInstStationId>();

template BOOL FOSEventTraceEnabled<_etguidDiskStationId>();

template BOOL FOSEventTraceEnabled<_etguidFileStationId>();

template BOOL FOSEventTraceEnabled<_etguidSysStationId>();

template BOOL FOSEventTraceEnabled<_etguidIsamDbfilehdrInfo>();

template BOOL FOSEventTraceEnabled<_etguidFmpStationId>();

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidInstStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidDiskStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidFileStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidSysStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidIsamDbfilehdrInfo>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidFmpStationId>(const TraceStationIdentificationReason);
