// POSIX equivalent of os/oseventtrace.cxx.  Upstream wraps the
// autogenerated MOF/ETW provider; on Linux this layer is the dispatch
// point for the LTTng tracepoint provider (libese_tracepoints.so),
// which libese.so dlopens at startup.  Until that provider lands the
// dispatch table stays null and every tracepoint is a no-op.
//
// Admin events (the three _etguidEventLog* IDs) used to be routed
// here from ETEventLogInfo/Warn/Error and written to stderr.  That
// path has moved to OSEventEmitToOsLog (eventoslog_posix.cxx, which
// emits to journald / syslog directly from OSEventReportEvent), so
// nothing in this file produces visible admin output anymore — the
// engine's ETEventLog* calls now flow through this dispatch on equal
// footing with every other tracepoint and only light up when the
// LTTng provider is loaded.
//
// This file still provides:
//
//   - Lifecycle entry points (no-ops)
//   - OSEventTrace_ stub (will be replaced with the LTTng dispatch
//     when libese_tracepoints.so lands)
//   - FOSEventTraceEnabled<>() always returning fFalse for the
//     handful of GUIDs explicitly instantiated in the header
//   - COSEventTraceIdCheck::FAnnounceTime<>() instantiations

#include "osstd.hxx"


////////////////////////////////////////////////
//  Lifecycle

void OSEventTracePostterm()
{
}

BOOL FOSEventTracePreinit() { return fTrue; }

void OSEventTraceTerm()
{
}

ERR ErrOSEventTraceInit() { return JET_errSuccess; }


////////////////////////////////////////////////
//  Trace recording (no-op until the LTTng provider is wired up)

void __cdecl OSEventTrace_( const ULONG /*etguid*/,
                            const size_t /*cData*/,
                            ... )
{
}


////////////////////////////////////////////////
//  Compile-time / runtime trace gates — always off
//
//  The header declares these as INLINE BOOL FOSEventTraceEnabled() and the
//  templated overload, plus extern template instantiations for the GUIDs
//  ESE actually checks. We provide the explicit instantiations here so the
//  engine links; all return fFalse so trace blocks are skipped.

//  Both FOSEventTraceEnabled overloads now have inline bodies in
//  oseventtrace.hxx (return fFalse). The explicit template
//  instantiations below still bind to the generic templated body
//  there, so the engine links for code paths that use the templated
//  form (e.g. `FOSEventTraceEnabled< _etguidCacheRequestPage >()`).

template BOOL FOSEventTraceEnabled<_etguidCacheRequestPage>();

template BOOL FOSEventTraceEnabled<_etguidCacheMemoryUsage>();

template BOOL FOSEventTraceEnabled<_etguidInstStationId>();

template BOOL FOSEventTraceEnabled<_etguidDiskStationId>();

template BOOL FOSEventTraceEnabled<_etguidFileStationId>();

template BOOL FOSEventTraceEnabled<_etguidSysStationId>();

template BOOL FOSEventTraceEnabled<_etguidIsamDbfilehdrInfo>();

template BOOL FOSEventTraceEnabled<_etguidFmpStationId>();

//  FAnnounceTime is INLINE in the header — only the explicit template
//  instantiations are needed here.
template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidInstStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidDiskStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidFileStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidSysStationId>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidIsamDbfilehdrInfo>(const TraceStationIdentificationReason);

template BOOL COSEventTraceIdCheck::FAnnounceTime<_etguidFmpStationId>(const TraceStationIdentificationReason);
