using System.Text;

namespace Mc;

internal static class HeaderEmitter
{
    public static void Emit(McFile file, CliOptions opts)
    {
        string stem = Path.GetFileNameWithoutExtension(opts.Input);
        string path = Path.Combine(opts.HeaderDir, stem + ".h");

        var sb = new StringBuilder();
        sb.Append("// Generated by mc (Linux). DO NOT EDIT.\n");
        sb.Append("// Source: ").Append(Path.GetFileName(opts.Input)).Append('\n');
        sb.Append("\n");
        sb.Append("#pragma once\n");
        sb.Append("\n");

        string typedef = file.MessageIdTypedef;

        foreach (var msg in file.Messages)
        {
            sb.Append("//\n");
            sb.Append("// MessageId: ").Append(msg.SymbolicName).Append('\n');
            sb.Append("//\n");
            sb.Append("// MessageText:\n");
            sb.Append("//\n");
            if (msg.Bodies.TryGetValue("English", out var body) || (msg.Bodies.Count > 0 && (body = msg.Bodies.Values.First()) is not null))
            {
                foreach (var line in body)
                {
                    sb.Append("// ").Append(line).Append('\n');
                }
            }
            sb.Append("//\n");
            sb.Append("#define ").Append(msg.SymbolicName).Append(' ');
            sb.Append("((").Append(typedef).Append(')').Append(msg.Id.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append("L)\n");
            sb.Append("\n");
        }

        File.WriteAllText(path, sb.ToString());
    }
}
