namespace Mc;

internal static class RcEmitter
{
    public static void EmitStub(McFile file, CliOptions opts)
    {
        string stem = Path.GetFileNameWithoutExtension(opts.Input);
        string path = Path.Combine(opts.RcDir, stem + ".rc");
        File.WriteAllText(path, "// Generated by mc (Linux): empty resource stub.\n");
    }
}

internal static class StubEmitter
{
    public static void EmitEmpty(CliOptions opts)
    {
        string stem = Path.GetFileNameWithoutExtension(opts.Input);
        File.WriteAllText(Path.Combine(opts.HeaderDir, stem + ".h"),
            "// Generated by mc (Linux): empty stub for ETW manifest.\n#pragma once\n");
        File.WriteAllText(Path.Combine(opts.RcDir, stem + ".rc"),
            "// Generated by mc (Linux): empty resource stub.\n");
    }
}
