using System.Globalization;
using System.Text;

namespace Mc;

//  Emits a C++ source file with the .mc messages baked into a sorted
//  static array of { id, const wchar_t* template } pairs.  Used by the
//  Linux port's FormatMessageW(FROM_HMODULE) implementation since there
//  is no Win32 .res section to look messages up in at runtime.
//
//  Wire-format note: const namespace-scope variables get internal
//  linkage in C++ unless an explicit `extern` says otherwise (the
//  `extern "C"` block does not override that).  Both the table and the
//  size are emitted with `extern` so the FormatMessageW TU resolves
//  them.
internal static class TableEmitter
{
    public static void Emit(McFile file, CliOptions opts)
    {
        string stem = Path.GetFileNameWithoutExtension(opts.Input);
        string path = Path.Combine(opts.CTableDir!, stem + "_table.cxx");

        var sorted = file.Messages
            .OrderBy(m => m.Id)
            .ToList();

        var sb = new StringBuilder();
        sb.Append("//  Generated by mc (Linux) from ").Append(Path.GetFileName(opts.Input)).Append(" — DO NOT EDIT.\n");
        sb.Append("//\n");
        sb.Append("//  Table of message templates used by FormatMessageW(FROM_HMODULE)\n");
        sb.Append("//  in the Linux port.  Sorted by id; winapi_message.cxx binary-searches.\n");
        sb.Append("//\n");
        sb.Append("//  Note: const namespace-scope variables get internal linkage in C++\n");
        sb.Append("//  unless an explicit `extern` says otherwise (extern \"C\" alone doesn't\n");
        sb.Append("//  do it).  Both definitions below use `extern` so the symbols are\n");
        sb.Append("//  exported and winapi_message.cxx's forward decls resolve.\n");
        sb.Append('\n');
        sb.Append("#include <stddef.h>\n");
        sb.Append('\n');
        sb.Append("extern \"C\"\n");
        sb.Append("{\n");
        sb.Append('\n');
        sb.Append("struct EseMsgTableEntry\n");
        sb.Append("{\n");
        sb.Append("    unsigned long  id;\n");
        sb.Append("    const wchar_t* sz;\n");
        sb.Append("};\n");
        sb.Append('\n');
        sb.Append("extern const EseMsgTableEntry g_rgEseMsgTable[] =\n");
        sb.Append("{\n");

        foreach (var msg in sorted)
        {
            string body = PreferredBody(msg);
            string escaped = EscapeWideLiteral(body);
            sb.Append("    { ");
            sb.Append(msg.Id.ToString(CultureInfo.InvariantCulture));
            sb.Append("UL, L\"");
            sb.Append(escaped);
            sb.Append("\" },\n");
        }

        sb.Append("};\n");
        sb.Append('\n');
        sb.Append("extern const size_t g_cEseMsgTable = ");
        sb.Append(sorted.Count.ToString(CultureInfo.InvariantCulture));
        sb.Append(";\n");
        sb.Append('\n');
        sb.Append("}  // extern \"C\"\n");

        File.WriteAllText(path, sb.ToString());
    }

    //  Pick the English body if present, otherwise the first language
    //  in declaration order — mirrors the convention HeaderEmitter uses.
    private static string PreferredBody(McMessage msg)
    {
        if (msg.Bodies.TryGetValue("English", out var english))
        {
            return string.Join('\n', english);
        }
        if (msg.Bodies.Count > 0)
        {
            return string.Join('\n', msg.Bodies.Values.First());
        }
        return string.Empty;
    }

    //  Escape a string for embedding inside L"..." in C++ source.
    //  FormatMessage's runtime escapes (%n, %t, %r, %0, %1..%99, %%) are
    //  preserved verbatim — they get processed when FormatMessageW
    //  expands the template at runtime, not at generation time.
    //
    //  Non-ASCII code points use 4-digit \xNNNN escapes so the escape
    //  never accidentally swallows a following digit (wchar_t is 16-bit
    //  under -fshort-wchar).
    private static string EscapeWideLiteral(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    if (c < 0x20)
                    {
                        sb.Append("\\x").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else if (c < 0x7f)
                    {
                        sb.Append(c);
                    }
                    else
                    {
                        sb.Append("\\x").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    break;
            }
        }
        return sb.ToString();
    }
}
